server:
  port: 9999

spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order/**
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
